[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "unitum"
version = "0.1.0"
description = "Templated rendering of project artefacts"
requires-python = ">=3.11"

[tool.setuptools.packages.find]
where = ["src"]

[tool.pytest.ini_options]
pythonpath = ["src"]
filterwarnings = [
    "ignore::DeprecationWarning"
]

[tool.black]
line-length = 120
target-version = ["py311"]
include = "\\.pyi?$"
extend-exclude = '''
/(
  \.venv
  | build
  | dist
)/
'''
